echo on 

@REM DATE/T skilar dagsetningu eins og lau. 23.02.2008 - dagsetning lesin inn í viðeigandi breytur:
FOR /F "TOKENS=1* DELIMS=. " %%i IN ('DATE/T') DO SET CDATE=%%j
FOR /F "TOKENS=1 DELIMS=. " %%i IN ('echo %CDATE%') DO SET DAGS=%%i
FOR /F "TOKENS=2 DELIMS=. " %%i IN ('echo %CDATE%') DO SET MAN=%%i
FOR /F "TOKENS=3 DELIMS=. " %%i IN ('echo %CDATE%') DO SET AR=%%i
SET AR_SHORT=%AR:~2%


SET WGET_COMMAND="C:\Program Files\GnuWin32\bin\wget.exe"
@REM SET ACROBAT_COMMAND="C:\Program Files\Adobe\Reader 8.0\Reader\AcroRd32.exe"
SET ACROBAT_COMMAND="C:\Program Files\Foxit Software\Foxit Reader\Foxit Reader.exe"


SET FRETTABLADID_FOLDER=C:\blod\frettabladid\
SET FRETTABLADID_BASE_URL=http://www.visir.is/ExternalData/pdf/fbl/
SET FRETTABLADID_TODAYS_FILE=%AR_SHORT%%MAN%%DAGS%.pdf

SET TUTTU4STUNDIR_FOLDER=C:\blod\24stundir\
SET TUTTU4STUNDIR_BASE_URL=http://www.mbl.is/bladidnet/%AR%-%MAN%/
SET TUTTU4STUNDIR_TODAYS_FILE=%AR%-%MAN%-%DAGS%.pdf

SET MBL_FOLDER=C:\blod\mogginn\
SET MBL_USER_KEY=xxxxx-xxxx-xxxxx
SET MBL_SESSION_ID=xxxxxxxxxx
SET MBL_BASE_URL=http://mbl.is/bladid/askr/
SET MBL_TODAYS_FILE_PRE=%MBL_USER_KEY%,%AR%-%MAN%-%DAGS%,
SET MBL_TODAYS_FILE_POST=%AR%-%MAN%-%DAGS%.pdf?t=%MBL_SESSION_ID%
SET MBL_TODAYS_FILE_A=%MBL_TODAYS_FILE_PRE%A%MBL_TODAYS_FILE_POST%
SET MBL_TODAYS_FILE_B=%MBL_TODAYS_FILE_PRE%B%MBL_TODAYS_FILE_POST%
SET MBL_TODAYS_FILE_C=%MBL_TODAYS_FILE_PRE%C%MBL_TODAYS_FILE_POST%
SET MBL_TODAYS_FILE_D=%MBL_TODAYS_FILE_PRE%D%MBL_TODAYS_FILE_POST%
SET MBL_TODAYS_FILE_E=%MBL_TODAYS_FILE_PRE%E%MBL_TODAYS_FILE_POST%
SET MBL_TODAYS_FILE_F=%MBL_TODAYS_FILE_PRE%F%MBL_TODAYS_FILE_POST%


CD %FRETTABLADID_FOLDER%
%WGET_COMMAND% %FRETTABLADID_BASE_URL%%FRETTABLADID_TODAYS_FILE%

CD %TUTTU4STUNDIR_FOLDER%
%WGET_COMMAND% %TUTTU4STUNDIR_BASE_URL%%TUTTU4STUNDIR_TODAYS_FILE%

@REM CD %MBL_FOLDER%
@REM %WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_A%
@REM %WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_B%
@REM %WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_C%
@REM %WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_D%
@REM %WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_E%
@REM %WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_F%


IF EXIST %FRETTABLADID_FOLDER%%FRETTABLADID_TODAYS_FILE% start %ACROBAT_COMMAND% %FRETTABLADID_FOLDER%%FRETTABLADID_TODAYS_FILE%

IF EXIST %TUTTU4STUNDIR_FOLDER%%TUTTU4STUNDIR_TODAYS_FILE% start %ACROBAT_COMMAND% %TUTTU4STUNDIR_FOLDER%%TUTTU4STUNDIR_TODAYS_FILE%

@REM IF EXIST "%MBL_FOLDER%%MBL_TODAYS_FILE_A%" %ACROBAT_COMMAND% %MBL_FOLDER%%MBL_TODAYS_FILE_A%
@REM IF EXIST "%MBL_FOLDER%%MBL_TODAYS_FILE_B%" %ACROBAT_COMMAND% %MBL_FOLDER%%MBL_TODAYS_FILE_B%
@REM IF EXIST "%MBL_FOLDER%%MBL_TODAYS_FILE_C%" %ACROBAT_COMMAND% %MBL_FOLDER%%MBL_TODAYS_FILE_C%
@REM IF EXIST "%MBL_FOLDER%%MBL_TODAYS_FILE_D%" %ACROBAT_COMMAND% %MBL_FOLDER%%MBL_TODAYS_FILE_D%
@REM IF EXIST "%MBL_FOLDER%%MBL_TODAYS_FILE_E%" %ACROBAT_COMMAND% %MBL_FOLDER%%MBL_TODAYS_FILE_E%
@REM IF EXIST "%MBL_FOLDER%%MBL_TODAYS_FILE_F%" %ACROBAT_COMMAND% %MBL_FOLDER%%MBL_TODAYS_FILE_F%
