echo on 

@REM DATE/T skilar dagsetningu eins og lau. 23.02.2008 - dagsetning lesin inn í viðeigandi breytur:
FOR /F "TOKENS=1* DELIMS=. " %%i IN ('DATE/T') DO SET CDATE=%%j
FOR /F "TOKENS=1 DELIMS=. " %%i IN ('echo %CDATE%') DO SET DAGS=%%i
FOR /F "TOKENS=2 DELIMS=. " %%i IN ('echo %CDATE%') DO SET MAN=%%i
FOR /F "TOKENS=3 DELIMS=. " %%i IN ('echo %CDATE%') DO SET AR=%%i
SET AR_SHORT=%AR:~2%


SET WGET_COMMAND="C:\Program Files\GnuWin32\bin\wget.exe"

SET BASE_FOLDER=C:\blod\
IF NOT EXIST %BASE_FOLDER% MD %BASE_FOLDER%

SET FRETTABLADID_FOLDER=%BASE_FOLDER%frettabladid\
IF NOT EXIST %FRETTABLADID_FOLDER% MD %FRETTABLADID_FOLDER%
SET FRETTABLADID_BASE_URL=http://www.visir.is/ExternalData/pdf/fbl/
SET FRETTABLADID_TODAYS_FILE=%AR_SHORT%%MAN%%DAGS%.pdf

SET TUTTU4STUNDIR_FOLDER=%BASE_FOLDER%24stundir\
IF NOT EXIST %TUTTU4STUNDIR_FOLDER% MD %TUTTU4STUNDIR_FOLDER%
SET TUTTU4STUNDIR_BASE_URL=http://www.mbl.is/bladidnet/%AR%-%MAN%/
SET TUTTU4STUNDIR_TODAYS_FILE=%AR%-%MAN%-%DAGS%.pdf

SET MBL_FOLDER=%BASE_FOLDER%mogginn\
IF NOT EXIST %MBL_FOLDER% MD %MBL_FOLDER%

SET MBL_BASE_URL=http://mbl.is/mm/mogginn/blad_dagsins/pdf//%AR%-%MAN%-%DAGS%/
SET MBL_TODAYS_FILE_PRE=%MBL_USER_KEY%,%AR%-%MAN%-%DAGS%,
SET MBL_TODAYS_FILE_POST=%AR%-%MAN%-%DAGS%.pdf?t=%MBL_SESSION_ID%
SET MBL_TODAYS_FILE_A=A%AR%-%MAN%-%DAGS%.pdf
SET MBL_TODAYS_FILE_B=B%AR%-%MAN%-%DAGS%.pdf
SET MBL_TODAYS_FILE_C=C%AR%-%MAN%-%DAGS%.pdf
SET MBL_TODAYS_FILE_D=D%AR%-%MAN%-%DAGS%.pdf
SET MBL_TODAYS_FILE_E=E%AR%-%MAN%-%DAGS%.pdf
SET MBL_TODAYS_FILE_F=F%AR%-%MAN%-%DAGS%.pdf
SET MBL_TODAYS_FILE_G=G%AR%-%MAN%-%DAGS%.pdf
SET MBL_TODAYS_FILE_H=H%AR%-%MAN%-%DAGS%.pdf
SET MBL_TODAYS_FILE_I=I%AR%-%MAN%-%DAGS%.pdf


CD %FRETTABLADID_FOLDER%
%WGET_COMMAND% %FRETTABLADID_BASE_URL%%FRETTABLADID_TODAYS_FILE%

CD %TUTTU4STUNDIR_FOLDER%
%WGET_COMMAND% %TUTTU4STUNDIR_BASE_URL%%TUTTU4STUNDIR_TODAYS_FILE%

CD %MBL_FOLDER%
%WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_A%
%WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_B%
%WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_C%
%WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_D%
%WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_E%
%WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_F%
%WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_G%
%WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_H%
%WGET_COMMAND% %MBL_BASE_URL%%MBL_TODAYS_FILE_I%


IF EXIST %FRETTABLADID_FOLDER%%FRETTABLADID_TODAYS_FILE% START %FRETTABLADID_FOLDER%%FRETTABLADID_TODAYS_FILE%

IF EXIST %TUTTU4STUNDIR_FOLDER%%TUTTU4STUNDIR_TODAYS_FILE% START %TUTTU4STUNDIR_FOLDER%%TUTTU4STUNDIR_TODAYS_FILE%

IF EXIST %MBL_FOLDER%%MBL_TODAYS_FILE_A% START %MBL_FOLDER%%MBL_TODAYS_FILE_A%
IF EXIST %MBL_FOLDER%%MBL_TODAYS_FILE_B% START %MBL_FOLDER%%MBL_TODAYS_FILE_B%
IF EXIST %MBL_FOLDER%%MBL_TODAYS_FILE_C% START %MBL_FOLDER%%MBL_TODAYS_FILE_C%
IF EXIST %MBL_FOLDER%%MBL_TODAYS_FILE_D% START %MBL_FOLDER%%MBL_TODAYS_FILE_D%
IF EXIST %MBL_FOLDER%%MBL_TODAYS_FILE_E% START %MBL_FOLDER%%MBL_TODAYS_FILE_E%
IF EXIST %MBL_FOLDER%%MBL_TODAYS_FILE_F% START %MBL_FOLDER%%MBL_TODAYS_FILE_F%
IF EXIST %MBL_FOLDER%%MBL_TODAYS_FILE_G% START %MBL_FOLDER%%MBL_TODAYS_FILE_G%
IF EXIST %MBL_FOLDER%%MBL_TODAYS_FILE_H% START %MBL_FOLDER%%MBL_TODAYS_FILE_H%
IF EXIST %MBL_FOLDER%%MBL_TODAYS_FILE_I% START %MBL_FOLDER%%MBL_TODAYS_FILE_I%
